name: pytorch_flutter_ffi_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
  "flutter": "3.3.8" # So you know what Flutter version was used to build this project. (Note that upper constraint doesn't work yet https://github.com/flutter/flutter/issues/95472)

dependencies:
  flutter:
    sdk: flutter
  native_pytorch:
    path: native_pytorch
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ml_models/functional_external_model.pt
